---
apiVersion: v1
type: opaque
kind: Secret
metadata:
  name: {{ include "scim.fullname" . }}-config
  labels:
    {{- include "scim.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: {{ .Values.log_level | default "info" }}

    server:
      listen_address: ":{{ include "scim.port" . }}"
      certs:
        tls_key_path: '/https-certs/tls.key'
        tls_cert_path: '/https-certs/tls.crt'
        tls_ca_cert_path: '/https-certs/ca.crt'
      auth:
        basic:
          enabled: {{ .Values.auth.basic.enabled | default "true" }}
          username: {{ .Values.auth.basic.username | default "scim" }}
        bearer:
          enabled: {{ .Values.auth.bearer.enabled | default "true" }}
    directory:
      {{- include "aserto-lib.rootDirectoryClient" . | nindent 6 }}
    scim:
      create_email_identities: {{ .Values.createEmailIdentities  }}
      create_role_groups: {{ .Values.createRoleGroups }}
      user_object_type: {{ .Values.userObjectType }}
      identity_object_type: {{ .Values.identityObjectType }}
      identity_relation: {{ .Values.identityRelation }}
      group_object_type: {{ .Values.groupObjectType }}
      group_member_relation: {{ .Values.groupMemberRelation }}
      group_mappings:
        {{- .Values.groupMappings | toYaml | nindent 8 }}
      user_mappings:
        {{- .Values.userMappings | toYaml | nindent 8 }}
